---
title: "DATA605 Homework 2"
author: "Andrew Bowen"
date: "2023-02-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```





## A = LU Factorization
First, let's define our function(s) to factorize a given square matrix A into lower and upper triangular matrices: [$A= LU$](https://en.wikipedia.org/wiki/LU_decomposition):

```{r}
# create test 3x3 matrix
sample_matrix <- matrix(data=c(1,2,3,4,5,6,7,8,9), nrow=3, ncol=3)
```

Adding some helper functions that will be called in `lu_factorization`
```{r}
get_multiplier <- function(r_i, r_j){
  # Gets multiplier that cancels out r_j: r_j - k * r_i = 0
   r_j / r_i
}

baseL <- function(N){
  # Returns "base" lower-triangular matrix: L
  L <- matrix(data=NA, nrow=N, ncol=N)
  # setting diagonal vals to 1 and upper triangular vals to 0
  for (i in seq(N)){
    for (j in seq(N))
      # Set diagonal vals to 1
      if (i == j){
        L[i, j] = 1
      }
      # Set lower triangular vals to 0
      else if(j > i){
        L[i, j] = 0
      }
  }
  return(L)
}

baseU <- function(N){
  # Returns "base" upper-triangular matrix: U
  U <- matrix(data=NA, nrow=N, ncol=N)
  # setting diagonal vals to 1 and upper triangular vals to 0
  for (i in seq(N)){
    for (j in seq(N))
      # Set diagonal vals to 1
      if (i == j){
        U[i, j] = 1
      }
      # Set lower triangular vals to 0
      else if(i > j){
        U[i, j] = 0
      }
  }
  return(U)
}
```

```{r factorization-function}

lu_factorization <- function(A){
  # A is square, so n x n by definition
  n <- nrow(A)
  L <- baseL(n)
  U <- baseU(n)
  
  # we can take the top row of A to be the top row of U as well
  U[1, ] = A[1, ]
  
  for (i in seq(n)){
    if (i > 1) {
      print(i)
      for (j in seq(n)){
        if (j < i && j != 0){
          print(j)
          print("Foo")
          k <- get_multiplier(A[i-1, j], A[i, j])
          L[i, j] = k
          
          # TODO: figure out accessing the multiplier for row operations to construct U
          # Subtract the jth row from the i + 1th row (keep i as main index)
          print(U[i, ])
          print(k)
          U[i, ] = A[i, ] - k * A[i-1, ]
          
        }
        
      }
    }
  }
  print(L)
  print(U)
}
sample_matrix_2x2 <-matrix(c(1,2,3,4), nrow=2, ncol=2)
lu_factorization(sample_matrix)
```

```{r}
test_matrix <- matrix(data=c(2, 2, 3, 5, 9, 10, 4, 1, 2), nrow=3, ncol=3)

lu_factorization(test_matrix)
```
